language: python
python: 3.6
dist: focal
services: docker

cache:
  directories:
  - $HOME/.ccache
  - $HOME/.cache/pip

env:
  global:
  - REPO_DIR=Shapely
  - BUILD_COMMIT=1.8.2
  - PLAT=x86_64
  - UNICODE_WIDTH=32
  - USE_CCACHE=1

deploy:
  provider: s3
  access_key_id: "$ARTIFACTS_KEY"
  secret_access_key: "$ARTIFACTS_SECRET"
  bucket: "$ARTIFACTS_BUCKET"
  skip_cleanup: true
  upload-dir: "${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}"
  local_dir: wheelhouse
  on:
    repo: "mapbox/shapely-wheels"
    all-branches: true

jobs:
  include:
  - name: "3.8 aarch64"
    os: linux
    arch: arm64-graviton2
    group: edge
    virt: vm
    env:
    - USE_CCACHE=0
    - PLAT=aarch64
    - MB_ML_VER=2014
    - MB_PYTHON_VERSION=3.8
    - NP_BUILD_DEP=numpy==1.19.5
    - DOCKER_TEST_IMAGE=multibuild/focal_{PLAT} NP_TEST_DEP=numpy==1.19.5
  - name: "3.9 aarch64"
    os: linux
    arch: arm64-graviton2
    group: edge
    virt: vm
    env:
    - USE_CCACHE=0
    - PLAT=aarch64
    - MB_ML_VER=2014
    - MB_PYTHON_VERSION=3.9
    - NP_BUILD_DEP=numpy==1.19.5
    - DOCKER_TEST_IMAGE=multibuild/focal_{PLAT} NP_TEST_DEP=numpy==1.19.5
  - name: "3.10 aarch64"
    os: linux
    arch: arm64-graviton2
    group: edge
    virt: vm
    env:
    - USE_CCACHE=0
    - PLAT=aarch64
    - MB_ML_VER=2014
    - MB_PYTHON_VERSION=3.10
    - NP_BUILD_DEP=numpy==1.21.2
    - DOCKER_TEST_IMAGE=multibuild/focal_{PLAT} NP_TEST_DEP=numpy==1.21.2

before_install:
    - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
    - BUILD_DEPENDS="$NP_BUILD_DEP cython==0.29.28 wheel==0.34.2"
    - TEST_DEPENDS="$NP_TEST_DEP attrs==21.2.0 pytest==6.2.5 boto3 packaging hypothesis==6.23.2 wheel==0.34.2 $GEN_DEPS"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT
    - ls -l ${TRAVIS_BUILD_DIR}/wheelhouse/
    - unzip -l ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl

script:
    - install_run $PLAT
